#!/bin/bash

# Forge Slackbuild for yml...
# This slackbuild is for dev dont use it please...

cd $(dirname $0) ; CWD=$(pwd)

PRGNAM=timedated
VERSION=${VERSION:-2026_master1.0}
BUILD=${BUILD:-1}
TAG=${TAG:-_FRG}
PKGTYPE=${PKGTYPE:-txz}

if [ -z "$ARCH" ]; then
  case "$( uname -m )" in
    i?86) ARCH=i586 ;;
    arm*) ARCH=arm ;;
       *) ARCH=$( uname -m ) ;;
  esac
fi

if [ ! -z "${PRINT_PACKAGE_NAME}" ]; then
  echo "$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE"
  exit 0
fi

TMP=${TMP:-/tmp/FORGE}
PKG=$TMP/package-$PRGNAM
OUTPUT=${OUTPUT:-/tmp}

if [ "$ARCH" = "i586" ]; then
  SLKCFLAGS="-O2 -march=i586 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "i686" ]; then
  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
  LIBDIRSUFFIX=""
elif [ "$ARCH" = "x86_64" ]; then
  SLKCFLAGS="-O2 -fPIC"
  LIBDIRSUFFIX="64"
else
  SLKCFLAGS="-O2"
  LIBDIRSUFFIX=""
fi

set -e

rm -rf $PKG $TMP
mkdir -p $TMP $PKG $OUTPUT
cd $TMP
cp -R $CWD/* .

chown -R root:root .
find . -type f \( -perm -4000 -o -perm -2000 \) -exec chmod -s {} +
find . ! -type l -type d ! -perm 755 -exec chmod -f 755 {} +
find . ! -type l -type f -perm /111 ! -perm 755 -exec chmod -f 755 {} +
find . ! -type l -type f ! -perm /111 ! -perm 644 -exec chmod -f 644 {} +

mkdir build
cd build
  CFLAGS="$SLKCFLAGS" \
  CXXFLAGS="$SLKCFLAGS" \
  meson setup \
    --prefix=/usr \
    --libdir=lib${LIBDIRSUFFIX} \
    --libexecdir=/usr/libexec \
    --buildtype=release \
    --strip \
    -Dprivileged-group=wheel \
    -Dhwclock_conf=/etc/hardwareclock \
    -Dadjtime_conf=/etc/adjtime \
    -Dntpd_conf=/etc/ntp.conf \
    -Dntpd_rc=/etc/rc.d/rc.ntpd \
    ..
  "${NINJA:=ninja}"
  DESTDIR=$PKG $NINJA install
cd ..

mkdir -p $PKG/usr/bin
cat timedatectl > $PKG/usr/bin/timedatectl
chmod +x $PKG/usr/bin/timedatectl

find $PKG -print0 | xargs -0 file | grep -e "executable" -e "shared object" | grep ELF \
  | cut -f 1 -d : | xargs strip --strip-unneeded 2> /dev/null || true


mkdir -p $PKG/install
cat $CWD/slack-desc > $PKG/install/slack-desc

cd $PKG
/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.$PKGTYPE
